"""'account'

Revision ID: 1caeeb8d42c8
Revises: a352daed5e31
Create Date: 2017-11-22 23:10:46.635349

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1caeeb8d42c8'
down_revision = 'a352daed5e31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qq', sa.String(length=12), nullable=True),
    sa.Column('email', sa.String(length=32), nullable=True),
    sa.Column('password', sa.String(length=32), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('_id', sa.String(length=128), nullable=True),
    sa.Column('max_down', sa.Integer(), nullable=True),
    sa.Column('current_down', sa.Integer(), nullable=True),
    sa.Column('cookie', sa.Text(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('png', '_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('png', 'bianhao',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('png', 'cat',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('png', 'cat_1',
               existing_type=mysql.TINYINT(display_width=2),
               nullable=True)
    op.alter_column('png', 'created',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('png', 'down',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('png', 'dpi',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('png', 'fav',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('png', 'format',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('png', 'img',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('png', 'is_spider',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('png', 'size',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('png', 'title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('png', 'url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('png', 'view',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('png', 'width',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.drop_index('url', table_name='png')
    op.create_unique_constraint(None, 'png', ['_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'png', type_='unique')
    op.create_index('url', 'png', ['url'], unique=True)
    op.alter_column('png', 'width',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('png', 'view',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('png', 'url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('png', 'title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('png', 'size',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('png', 'is_spider',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('png', 'img',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('png', 'format',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('png', 'fav',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('png', 'dpi',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('png', 'down',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('png', 'created',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('png', 'cat_1',
               existing_type=mysql.TINYINT(display_width=2),
               nullable=False)
    op.alter_column('png', 'cat',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('png', 'bianhao',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('png', '_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_table('account')
    # ### end Alembic commands ###
