"""empty message

Revision ID: cd4e9a614fc5
Revises: a866df4ecef2
Create Date: 2017-11-19 20:25:34.735001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd4e9a614fc5'
down_revision = 'a866df4ecef2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('avatar', sa.String(length=64), nullable=True),
    sa.Column('auth_key', sa.String(length=128), nullable=True),
    sa.Column('access_token', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('reg_ip', sa.String(length=32), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_qq',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qq_openid', sa.String(length=64), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_qq')
    op.drop_table('user')
    # ### end Alembic commands ###
